### ISSUE TITLE
medtype-as-service

### ISSUE THREAD

**Issue by ayush-raj7** [svjan5/medtype#4]
Hi,
I am running medtype-as-server. While running when I am starting the server using the following command :

```
medtype-serving-start --model_path $PWD/resources/pretrained_models/pubmed_model.bin \
		      --type_remap_json $PWD/../config/type_remap.json \
		      --type2id_json $PWD/../config/type2id.json \
		      --umls2type_file $PWD/resources/umls2type.pkl \ 
		      --entity_linker scispacy
```
`
I am getting the following error:

```
I:VENTILATOR:[__i:__i: 64]:freeze, optimize and export graph, could take a while...
Traceback (most recent call last):
  File "/opt/conda/bin/medtype-serving-start", line 33, in <module>
    sys.exit(load_entry_point('medtype-serving-server==1.0.0', 'console_scripts', 'medtype-serving-start')())
  File "/opt/conda/lib/python3.6/site-packages/medtype_serving_server-1.0.0-py3.6.egg/medtype_serving/server/cli/__init__.py", line 4, in main
    with MedTypeServer(get_run_args()) as server:
  File "/opt/conda/lib/python3.6/site-packages/medtype_serving_server-1.0.0-py3.6.egg/medtype_serving/server/__init__.py", line66, in __init__
    self.model_params   = self.load_model(args.model_path)
  File "/opt/conda/lib/python3.6/site-packages/medtype_serving_server-1.0.0-py3.6.egg/medtype_serving/server/__init__.py", line74, in load_model
    state               = torch.load(model_path, map_location="cpu")
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
```

I tried loading the pretrained model using torch version: 1.8.0 and using code :
`model = torch.load('pubmed_model.bin', map_location="cpu")`
It loaded successfully.
But when I did it using  torch version: 1.4.0
I got same error as above.

Is the pretrained model present in the medtype github repo, trained on a different pytorch version? Or is there any other problem? Please let me know the way to solve it.

Thanks

**Comment by amirj** [comment]
I have the same problem. @ayush-raj7 could you solve this issue?

**Comment by dlrenz** [comment]
Changing the torch requirement from torch==1.4.0 to torch==1.8.0 in setup.py before installation seems to work fine for me.

**Comment by svjan5** [comment]
Thanks a lot @dlrenz!
